from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from backend.config import get_settings

router = APIRouter()
settings = get_settings()


class DraftRequest(BaseModel):
    document_type: str = Field(..., min_length=1)
    parties: str = Field(..., min_length=1)
    terms: str = Field(..., min_length=1)
    effective_date: Optional[str] = None
    title: Optional[str] = None
    jurisdiction: Optional[str] = None
    language: str = "English"


def _clean_lines(value: str) -> list[str]:
    cleaned = [entry.strip() for entry in value.split(";")]
    cleaned = [entry for entry in cleaned if entry]
    return cleaned or [value.strip()]


def _build_document_text(payload: DraftRequest) -> str:
    title = (payload.title or payload.document_type).strip() or "Legal Document"
    effective_date = payload.effective_date or "TBD"
    jurisdiction = payload.jurisdiction.strip() if payload.jurisdiction else "Not specified"

    terms = _clean_lines(payload.terms)
    section_lines = [
        title.upper(),
        "",
        f"Effective Date: {effective_date}",
        f"Jurisdiction: {jurisdiction}",
        f"Language: {payload.language}",
        "",
        "PARTIES",
        payload.parties.strip(),
        "",
        "TERMS AND CONDITIONS",
    ]

    for index, term in enumerate(terms, start=1):
        section_lines.append(f"{index}. {term}")

    section_lines.extend([
        "",
        "This draft is generated by LegalEase for review and should be validated by a qualified legal professional before use.",
    ])
    return "\n".join(section_lines)


@router.get("/health")
def route_health() -> dict:
    return {
        "status": "ok",
        "gemini_configured": bool(settings.gemini_api_key),
        "model": settings.gemini_model,
    }


@router.post("/generate")
def generate_document(payload: DraftRequest) -> dict:
    if not payload.parties.strip():
        raise HTTPException(status_code=400, detail="Please provide the parties involved.")
    if not payload.terms.strip():
        raise HTTPException(status_code=400, detail="Please provide the terms and conditions.")

    content = _build_document_text(payload)
    return {
        "content": content,
        "model": settings.gemini_model,
        "document_type": payload.document_type,
    }
